config/routes.rb
#Šeit tiek veidots ceļs, kas atļauj pāriet uz lapu lapā.
Rails.application.routes.draw do
  resources :darbiniekis
  #get 'home/index'
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/darbinieki.rb
class Darbinieki < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/darbiniekis_controller.rb
class DarbiniekisController < ApplicationController
  before_action :set_darbinieki, only: %i[ show edit update destroy ]

  # GET /darbiniekis or /darbiniekis.json
  def index
    @darbiniekis = Darbinieki.all
  end

  # GET /darbiniekis/1 or /darbiniekis/1.json
  def show
  end

  # GET /darbiniekis/new
  def new
    @darbinieki = Darbinieki.new
  end

  # GET /darbiniekis/1/edit
  def edit
  end

  # POST /darbiniekis or /darbiniekis.json
  def create
    @darbinieki = Darbinieki.new(darbinieki_params)

    respond_to do |format|
      if @darbinieki.save
        format.html { redirect_to @darbinieki, notice: "Darbinieki was successfully created." }
        format.json { render :show, status: :created, location: @darbinieki }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @darbinieki.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /darbiniekis/1 or /darbiniekis/1.json
  def update
    respond_to do |format|
      if @darbinieki.update(darbinieki_params)
        format.html { redirect_to @darbinieki, notice: "Darbinieki was successfully updated." }
        format.json { render :show, status: :ok, location: @darbinieki }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @darbinieki.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /darbiniekis/1 or /darbiniekis/1.json
  def destroy
    @darbinieki.destroy
    respond_to do |format|
      format.html { redirect_to darbiniekis_url, notice: "Darbinieki was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_darbinieki
      @darbinieki = Darbinieki.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def darbinieki_params
      params.require(:darbinieki).permit(:starta_laiks, :beigu_laiks, :vards, :uzvards, :epasts, :telefons)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/darbiniekis_helper.rb
module DarbiniekisHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/darbiniekis/_form.html.erb
<!--- Šis attiecās uz jaunas elektriskā velosipēda rezervācijas aizpildes lapu  --->
<%= form_with(model: darbinieki) do |form| %>
  <% if darbinieki.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(darbinieki.errors.count, "error") %> prohibited this darbinieki from being saved:</h2>

      <ul>
        <% darbinieki.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :vards, class:"form-control", placeholder: "Vārds" %>
  </div>

  <br/>

  <div class="field form-group">
    <%= form.text_field :uzvards, class:"form-control", placeholder: "Uzvārds" %>
  </div>

  <br/>

  <div class="field form-group">
    <%= form.text_field :epasts, class:"form-control", placeholder: "Epasts" %>
  </div>

  <br/>

  <div class="field form-group">
    <%= form.text_field :telefons, class:"form-control", placeholder: "Telefona numurs" %>
  </div>

  <br/>

  <div class="field form-group">
    <%= form.label :uzsākšanas_laiks %>
    <%= form.datetime_select :starta_laiks, class:"form-control" %>
  </div>

  <br/>

  <div class="field form-group">
    <%= form.label :nodošanas_laiks %>
    <%= form.datetime_select :beigu_laiks, class:"form-control" %>
  </div>

  <br/>

  <div class="actions">
    <%= form.submit class:'btn btn-success' %>
  </div>
<% end %>

app/views/darbiniekis/edit.html.erb
<!--- Šis attiecās uz nomātāju rediģēšanu, ja ir velme izlabot iesniegto --->
<h1>Rediģēt Nomātāju</h1>
<br/>


<%= render 'form', darbinieki: @darbinieki %>

<br/>

<%= link_to 'Info', @darbinieki, class: "btn btn-secondary" %> 
<%= link_to 'Atpakaļ', darbiniekis_path, class: "btn btn-dark" %>

app/views/darbiniekis/index.html.erb
<!--- Šeit tiek demostrēta Relācijas DB tabula kura sevī ietver visu informāciju par rezervācijām no cikiem līdz cikiem --->
<h1>Darbinieku saraksts</h1>

<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Uzsākšanas laiks:</th>
      <th>Nodošanas laiks:</th>
      <th>Vārds</th>
      <th>Uzvārds</th>
      <th>Epasts</th>
      <th>Telefons</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @darbiniekis.each do |darbinieki| %>
      <tr>
        <td><%= darbinieki.starta_laiks %></td>
        <td><%= darbinieki.beigu_laiks %></td>
        <td><%= darbinieki.vards %></td>
        <td><%= darbinieki.uzvards %></td>
        <td><%= darbinieki.epasts %></td>
        <td><%= darbinieki.telefons %></td>
        <td><%= link_to 'Info', darbinieki, class:"btn btn-outline-info btn-sm" %></td>
        <td><%= link_to 'Rediģēt', edit_darbinieki_path(darbinieki), class:"btn btn-outline-primary btn-sm" %></td>
        <td><%= link_to 'Dzēst', darbinieki, method: :delete, data: { confirm: 'Vai tu esi pārliecināts?' }, class: "btn btn-outline-danger btn-sm" %></td>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Rezervēt', new_darbinieki_path, class:"btn btn-secondary" %>

app/views/darbiniekis/new.html.erb
<!--- Šeit tiek ievadīta jauna rezervācija par elektorniskā velosipēda nomu --->
<h1>Jauna E-velosipēda rezervācija</h1>
<br/>

<%= render 'form', darbinieki: @darbinieki %>

<br/>

<%= link_to 'Uz Darbinieku sarakstu', darbiniekis_path, class: "btn btn-dark" %>

app/views/darbiniekis/show.html.erb
<!--- Šeit tiek parādīta informācija ja cilvēks vēlās paskatīties detaļās par noteikta cilvēka rezervāciju --->
<div class="jumbotron">
  <h1 class="display-4"><%= @darbinieki.vards %> <%= @darbinieki.uzvards %> </h1>
  <p class="lead"><%= @darbinieki.epasts %> | <%= @darbinieki.telefons %>  </p>
  <hr class="my-4">
  <p>
  <strong>Uzsākšanas laiks:</strong>
  <%= @darbinieki.starta_laiks %>
  </p>

  <p>
  <strong>Nodošanas laiks:</strong>
  <%= @darbinieki.beigu_laiks %>
  </p>
</div>

<%= link_to 'Rediģēt', edit_darbinieki_path(@darbinieki), class:"btn btn-primary" %> 
<%= link_to 'Atpakaļ', darbiniekis_path, class:"btn btn-secondary" %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to 'E-velosipēdu noma', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to "Nomas saraksts", darbiniekis_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Jauna rezervācija", new_darbinieki_path, class:"nav-link" %>
        </li>


      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>E-velosipēdu noma</h1> 
<br/>
<strong>Nomas saraksts:</strong> saraksts ar darbinieki kuri rezervēja elektrisko velosipēdu.
<br/>

<strong>Jauna rezervācija:</strong> ievadiet savus datus, lai izmantotu elektrisko velosipēdu.

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice%>

  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!--- Pievienoju klāt arī bootstrap, lai mājaslapa izskatītos labāk --->
<!doctype html> 
<html lang="en">
  <head>
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <title>E-velosipedi</title>

        <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= render 'home/header' %>
    <div class="container">
  <br/>
    <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>

      <%= yield %> 
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
  </body>
</html>